### ISSUE TITLE
Error: Method not found: 'MediaQuery.maybeOf

### ISSUE THREAD

**Issue by gabdsg** [aloisdeniel/tap_builder#2]
I'm getting this error  at `src/animated_tap_builder.dart:187:29`
`Error: Method not found: 'MediaQuery.maybeOf final mode = MediaQuery.maybeOf(context)?.navigationMode ?? `

**Comment by aloisdeniel** [comment]
Oh yes, I'm on the beta channel... This breaking change makes me mad !

I will publish a new version for stable and another dedicated to beta.

**Comment by gabdsg** [comment]
That's awesome!

**Comment by aloisdeniel** [comment]
That's published as `0.1.2`. It should work now. :)

**Comment by ZahidTekbas** [comment]
Hi Aloïs. 

I have used tap_builder: ^0.1.2 and I'm getting this error. 

`../../../flutter/.pub-cache/hosted/pub.dartlang.org/tap_builder-0.1.2/lib/src/animated_tap_builder.dart:187:29: Error: Method not found:
'MediaQuery.maybeOf'.
    final mode = MediaQuery.maybeOf(context)?.navigationMode ?? `

edit: 

this is my Flutter version:

`[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.14.6 18G87 darwin-x64, locale en-TR)
    • Flutter version 1.22.4 at /Users/zahidtekbas/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4`

**Comment by gabdsg** [comment]
Yes, version 0.1.2 still have a problem

**Comment by aloisdeniel** [comment]
Sorry, fixed with 0.1.3!
