### ISSUE TITLE
Error: Method not found

### ISSUE THREAD

**Issue by jaustinUF** [aloisdeniel/tap_builder#3]
Using exact copy of code, no compile-time errors.

Getting this runtime error:
Running Gradle task 'assembleDebug'...
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/tap_builder-0.1.2/lib/src/animated_tap_builder.dart:187:29: Error: Method not found: 'MediaQuery.maybeOf'. final mode = MediaQuery.maybeOf(context)?.navigationMode ??

I'm only a couple of months into Flutter/Dart, but this looks like error in the tap_builder package, not the app.
Comments/suggestions?

**Comment by wandbrandon** [comment]
same problem! Works fine on Android, but not on IOS

**Comment by aloisdeniel** [comment]
Could you try the [last 0.1.3 version](https://pub.dev/packages/tap_builder) ? 

@wandbrandon I suspect another issue on your side, not related to tap_builder. The package only relies on Flutter, if it works on Android, it should work on iOS too.

**Comment by wandbrandon** [comment]
appreciate the response. Upgrading to the beta branch solves the issue 
-------- Original message --------From: Aloïs Deniel <notifications@github.com> Date: 12/11/20  12:29 AM  (GMT-05:00) To: aloisdeniel/tap_builder <tap_builder@noreply.github.com> Cc: Brandon Wand <wandbrandon@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [aloisdeniel/tap_builder] Error: Method not found (#3) 
Could you try the last 0.1.3 version ?
@wandbrandon I suspect another issue on your side, not related to tap_builder. The package only relies on Flutter, if it works on Android, it should work on iOS too.
